name: PingKicker
version: ${project.version}
main: me.mikedev.com.pingkicker.PingKicker
authors: [MikeDEV]
description: Kick players if they have high ping!
commands:
  ping:
permissions:
  ping.ping:
    default: notop
  ping.other:
    default: op
  ping.reload:
    default: op
  ping.average:
    default: op
  ping.*:
    default: op
